---
- name: Vprofile ec2 setup 
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variable
      include_vars: vars/vpc_output_vars

    - name: Import vprofile setup variable
      include_vars: vars/vprostacksetup

    - name: Creating a vprofile ec2_key
      ec2_key:
        name: vprokey
        region: "{{region}}"
      register: vprokey_out

    - name: save private key into file loginkey_vpro.pem
      copy:
        content: "{{vprokey_out.key.private_key}}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed         
