- name: Set host to ip mapping in /etc/hosts file of all the instance in the stack
  hosts: all
  tasks:  
    - name: Import vpc setup variable
      include_vars: group_vars/hostip

    - name: Update hosts file for all the Hosts
      blockinfile:
        path: /etc/hosts
        block: |
          {{web01_ip}} web01
          {{app01_ip}} app01
          {{rmq01_ip}} rmq01
          {{mc01_ip}} mc01
          {{db01_ip}} db01